#pragma once
#include "../Core.h"
#include "Font.h"
#include "Script.h"

#if defined(__has_include)
    #if __has_include("RatUITextImpl.h")
        #include "RatUITextImpl.h"
        #define RATUI_TEXT_IMPL
    #elif __has_include(<RatUITextImpl.h>)
        #include <RatUITextImpl.h>
        #define RATUI_TEXT_IMPL
    #endif
#endif

namespace RatUI
{
    /**
     * @brief Represents the resolved string data for a Text value, along with a version number for caching purposes.
     * @warning 'Data' must remain valid as long as 'Version' is the latest version for the corresponding Text value. 
     * If the Text value changes and a new ResolvedText is generated, any previously obtained 'Data' may become invalid and should not be used.
     */
    struct ResolvedText
    {
        StringView Data;  ///< The actual string data to be rendered, resolved from the original Text value. This is what will be used for layout and rendering.
        u32 Version{ 0 }; ///< A version number that increments whenever the resolved string data changes for the same Text value. 
                          ///< This can be used for caching purposes, to avoid re-layout and re-rendering when the text content hasn't actually changed.
    };

#ifndef RATUI_TEXT_IMPL

    /**
     * @brief Used by widgets such as TextWidget to store the actual text content.
     * Text is treated as an opaque type that is only copied, moved, and converted to StringView via ResolveTextString(). 
     * By default, this is just a String alias, but users can provide their own implementation by defining a custom Text type.
     * This is useful for localisation systems that want to store text as keys or IDs and resolve them to actual strings at runtime, 
     * while still allowing widgets to treat text as an opaque value.
     */
    struct Text
    {
        String m_Data;
    };

    /**
     * @brief Converts a Text value to a ResolvedText, which contains the actual string data to be rendered and a version number for caching purposes.
     * @note This function shouldn't be too heavy since it is called every frame for every TextWidget.
     */
    inline Optional<ResolvedText> ResolveText( const Text& a_Text )
    {
        return ResolvedText{ StringView{ a_Text.m_Data }, 0u };
    } 

#endif


    /**
     * @brief Font-internal glyph index, generated by the shaping engine.
     */
    enum class GlyphID : u32 {};

    /**
     * @brief Specifies the base directionality of text for proper rendering of mixed-direction content.
     */
    enum class ETextDirection : u8
    {
        Auto, ///< Infer from the first strong character (Unicode Bidi Algorithm).
        LTR,  ///< Left-to-right text direction, used for scripts like Latin and Cyrillic.
        RTL,  ///< Right-to-left text direction, used for scripts like Arabic and Hebrew.

        _NumBits = 2
    };

    /**
     * @brief Specifies the horizontal alignment of text within its layout box.
     */
    enum class ETextAlign : u8
    {
        Left,    ///< The text is aligned to the left edge of the layout box.
        Center,  ///< The text is centered horizontally within the layout box.
        Right,   ///< The text is aligned to the right edge of the layout box.
        Justify, ///< The text is stretched to fill the entire width of the layout box, with extra space distributed between words.

        _NumBits = 2
    };

    /**
     * @brief Specifies the vertical alignment of text relative to its layout box.
     */
    enum class ETextBaseline : u8
    {
        Top,       
        Middle,    
        Bottom,    
        Hanging,
        Alphabetic,

        _NumBits = 3
    };

    /**
     * @brief Specifies how to handle text that exceeds the available space in a layout.
     */
    enum class ETextOverflow : u8
    {
        Clip,     ///< Text that exceeds the available space is simply cut off, without any indication to the user.
        Ellipsis, ///< Text that exceeds the available space is truncated and an ellipsis ("...") is appended to indicate that there is more text that is not visible.
        Fade,     ///< Text that exceeds the available space gradually fades out, providing a visual cue that there is more text that is not visible.

        _NumBits = 2
    };

    /**
     * @brief Specifies text transformation rules for layout and rendering.
     */
    enum class ETextTransform : u8
    {
        None,       ///< No transformation is applied to the text; it is rendered as-is.
        Uppercase,  ///< All characters in the text are transformed to uppercase.
        Lowercase,  ///< All characters in the text are transformed to lowercase.
        Capitalize, ///< The first character of each word is transformed to uppercase.

        _NumBits = 2
    };

    /**
     * @brief Specifies how text should wrap when it reaches the edge of its layout box.
     */
    namespace EBreakMode
    {
        constexpr u8 None = 0; ///< No wrapping; text will continue on a single line and may overflow its container.
        constexpr u8 Word = 1; ///< Text will wrap at word boundaries, ensuring that words are not split across lines. 
                               ///< If a single word exceeds the container width, it will overflow.
        constexpr u8 Char = 2; ///< Text will wrap at any character boundary, allowing words to be split if necessary to fit within the container width.

        constexpr u8 _NumBits = 2;
    };

    /**
     * @brief Specifies how whitespace characters are handled during text layout and rendering.
     */
    namespace EWhitespace
    {
        constexpr u8 Preserve = 0; ///< Whitespace is preserved as-is. Text will only wrap on line breaks.
        constexpr u8 Collapse = 1; ///< Sequences of whitespace will collapse into a single whitespace. Text will wrap when necessary.

        constexpr u8 _NumBits = 1;
    };

    /**
     * @brief Specifies how newline characters are handled during text layout and rendering.
     */
    namespace ENewline
    {
        constexpr u8 Preserve = 0; ///< Sequences of newlines will collapse into a single newline. Text will wrap when necessary, and on line breaks.
        constexpr u8 Collapse = 1; ///< Newlines are treated as whitespace and will collapse into a single whitespace. Text will wrap when necessary.

        constexpr u8 _NumBits = 1;
    };

    /**
     * @brief Defines text wrapping behavior, including line-breaking rules, whitespace handling, and newline handling.
     */
    struct TextWrap
    {
        u8 BreakMode  : EBreakMode::_NumBits  { EBreakMode::Word };
        u8 Whitespace : EWhitespace::_NumBits { EWhitespace::Collapse };
        u8 Newline    : ENewline::_NumBits    { ENewline::Preserve };

        /** @brief Determines if the text should be pre-wrapped - i.e., whether Prepare() should do an initial layout pass treating newlines as hard breaks. */
        constexpr bool Prewrap() const { return ( BreakMode != EBreakMode::None ) && ( Newline == ENewline::Preserve ); }

        constexpr bool operator==( const TextWrap& ) const = default;

        /** @brief Sequences of whitespace will collapse into a single whitespace. Text will never wrap to the next line. */
        static constexpr TextWrap NoWrap()   { return { EBreakMode::None, EWhitespace::Collapse, ENewline::Preserve }; }

        /** @brief Ordinary wrapping at word boundaries. Sequences of whitespace will collapse into a single whitespace. 
         *  Text will wrap when necessary, and on line breaks. */
        static constexpr TextWrap WrapWord() { return { EBreakMode::Word, EWhitespace::Collapse, ENewline::Preserve }; }

        /** @brief Aggressive wrapping at any character boundary. Sequences of whitespace will collapse into a single whitespace. 
         *  Text will wrap when necessary, and on line breaks. */
        static constexpr TextWrap WrapChar() { return { EBreakMode::Char, EWhitespace::Collapse, ENewline::Preserve }; }

        /** @brief Sequences of whitespace will be preserved as-is. Text will only wrap on line breaks. */
        static constexpr TextWrap Pre()      { return { EBreakMode::None, EWhitespace::Preserve, ENewline::Preserve }; }

        /** @brief Sequences of whitespace will collapse into a single whitespace. Text will only wrap on line breaks. */
        static constexpr TextWrap PreLine()  { return { EBreakMode::Word, EWhitespace::Collapse, ENewline::Preserve }; }

        /** @brief Sequences of whitespace will be preserved as-is. Text will wrap at word boundaries, and on line breaks. 
         *  Newlines will be treated as whitespace and will collapse into a single whitespace. */
        static constexpr TextWrap PreWrap()  { return { EBreakMode::Word, EWhitespace::Preserve, ENewline::Preserve }; }

        /** @brief A default text wrap configuration that provides ordinary wrapping at word boundaries. */
        static constexpr TextWrap Normal() { return WrapWord(); }
    };
    static_assert( TextWrap{} == TextWrap::WrapWord(), "Default TextWrap should be WrapWord" );
    static_assert( TextWrap::Normal() == TextWrap::WrapWord(), "TextWrap::Normal() should be WrapWord" );

    /**
	 * @brief A struct that encapsulates the styling information for layout of text.
     */
    struct TextLayoutStyle
    {
        FontHandle     Font              {}; ///< The font to use for rendering the text, specified as a FontHandle. If not set, a default font will be used.
        Unit           Size        { 16_u }; ///< The size of the font in points, which determines the height of the characters. Default is 16.0f.          
        Unit           LineHeight   { 0_u }; ///< The height of each line of text, including spacing. If set to 0, it will be automatically calculated based on the font size and metrics.
        Unit           LetterSpacing{ 0_u }; ///< The spacing between characters in the text, specified in points. Default is 0.0f.
		Unit           WordSpacing  { 0_u }; ///< The spacing between words in the text, specified in points. Default is 0.0f.
		Unit           LineSpacing  { 0_u }; ///< The additional spacing between lines of text, specified in points. Default is 0.0f.
		u32            MaxLines       { 0 }; ///< The maximum number of lines to display. If set to 0, there is no limit and all lines will be displayed.

        EScript        Script     { EScript::Invalid };
        ETextDirection Direction  { ETextDirection::Auto };
        TextWrap       Wrap       { TextWrap::Normal() }; 
        ETextOverflow  Overflow   { ETextOverflow::Clip };
        ETextTransform Transform  { ETextTransform::None };

		constexpr bool operator==( const TextLayoutStyle& ) const = default;
    };

	/**
	 * @brief A struct that encapsulates the styling information for rendering of text, such as color and decorations.
     */
    struct TextRenderStyle
    {
        f32           FadePercentage{ 0.25f };               ///< The percentage of the text width to use for the fade-out zone when ETextOverflow::Fade is selected.
                                                             ///< Default is 0.25 (25% of the text width).
		ETextAlign    Align{ ETextAlign::Left };             ///< The horizontal alignment of the text within its layout box. Default is left-aligned.
		ETextBaseline Baseline{ ETextBaseline::Top };        ///< The vertical alignment of the text relative to its layout box. Default is Top.
                                                             ///< This only affects the text's position if the layout box isn't content sized.
 
        bool Underline     : 1 = false; ///< Draws an underline decoration. Default is false.
        bool Strikethrough : 1 = false; ///< Draws a strikethrough decoration. Default is false.
        bool Shadow        : 1 = false; ///< Enables the drop shadow. Uses the Shadow* properties below. Default is false.
        bool Outline       : 1 = false; ///< Enables the outline. Uses the Outline* properties below. Default is false.
        bool Glow          : 1 = false; ///< Enables the outer glow. Uses the Glow* properties below. Default is false.
 
		// - Fill properties
 
		Color FillColor     { Colors::White }; ///< RGBA color of the glyph interior. Default is white.
		f32   FillSoftness  { 0.4f };          ///< Extra feathering added to the fill edge, in screen pixels. 0 = hard 1px AA edge. Default is 0.4.
		f32   FillThreshold { 0.445f };        ///< Threshold the SDF value must be greater than to be considered fully filled.
                                               ///< Lower values make the text bolder, higher values make it thinner. True default is 0.5, but 0.445 looks better for smaller text sizes.
 
		// - Outline properties
 
		Color OutlineColor    { Colors::White }; ///< RGBA color of the outline. Default is white.
		f32   OutlineWidth    { 0.1f };          ///< Thickness of the outline in SDF units [0, 0.5]. Larger values produce a thicker outline.
		                                         ///< The maximum useful value is 0.5, at which point the outline fills the entire glyph.
		                                         ///< Typical range is 0.05-0.2. Default is 0.1.
		f32   OutlineSoftness { 0.1f };          ///< Extra feathering on the outline's outer edge, in screen pixels. 0 = hard edge. Default is 0.1.
 
		// - Shadow properties
 
		Color ShadowColor    { Colors::Black }; ///< RGBA color of the drop shadow. Default is black.
        Vec2f ShadowOffset   { 4.f, 4.f };      ///< Shadow displacement in atlas pixels (X right, Y down). Converted to UV space
		                                        ///< automatically. Larger values move the shadow further from the glyph. Default is (4, 4).
		f32   ShadowSoftness { 1.0f };          ///< Blur radius of the shadow edge, in screen pixels. 0 = hard shadow. Default is 1.0.
		f32   ShadowSpread   { 0.05f };         ///< Dilates the shadow shape before blurring, in SDF units [0, 0.5].
		                                        ///< Positive values make the shadow larger than the glyph. Default is 0.05.
 
		// - Glow properties

		Color GlowColor  { Colors::White }; ///< RGBA color of the outer glow. Default is white.
		f32   GlowSpread { 1.f };           ///< Width of the glow band in SDF units. The glow extends outward from the outline edge
		                                    ///< (or fill edge if no outline) by this amount. Clamped internally to the usable SDF
		                                    ///< range - increase c_MsdfPxRange for wider glows. Default is 1.0.
		f32   GlowPower  { 1.5f };          ///< Falloff exponent for the glow intensity across the band.
		                                    ///< 1.0 = linear fade from the glyph edge outward.
		                                    ///< >1.0 = intensity concentrated near the glyph edge, faster falloff.
		                                    ///< <1.0 = wide flat halo with a gradual outer tail. Default is 1.5.
 
		constexpr bool operator==( const TextRenderStyle& ) const = default;
    };

    /**
	 * @brief Stores measurement results of a block of text created by ITextMetrics.
     */
    struct TextMeasurement
    {
        Vec2f Size{};         ///< The width and height of the measured text block.
        f32 Baseline{ 0.0f }; ///< The distance from the top of the text block to the baseline, which is important for aligning text vertically.
        u32 LineCount{ 0 };   ///< The number of lines in the measured text block, which can be used for multi-line text layout and spacing calculations.
    };

    /**
     * @brief The kind of a text segment.
     */
    enum class ESegmentKind : u8
    {
        Text,       ///< A word (Latin / script run) or a single CJK codepoint.
        Space,      ///< Collapsible inter-word whitespace.
        HardBreak,  ///< Explicit newline (only emitted in pre-wrap mode).
    };

    /**
     * @brief A single pre-measured segment of text.
     *
     * Each segment corresponds to a contiguous byte range inside
     * PreparedText::NormalizedText.
     */
    struct TextSegment
    {
        u32  StartByte{ 0 };    ///< Byte offset inside PreparedText::NormalizedText.
        u32  ByteLength{ 0 };   ///< Length in bytes.
        Unit Width{ 0_u };      ///< Point advance used for line-fit checks (includes any spacing).
        Unit PaintWidth{ 0_u }; ///< Point width of visible rendered content.
                                ///<   Text     : equals Width.
                                ///<   Space    : 0 (trailing spaces hang past the edge).
                                ///<   HardBreak: 0.

        ESegmentKind Kind{ ESegmentKind::Text };
        bool         IsCJKChar{ false }; ///< True when this is a single CJK codepoint.
    };

    /**
     * @brief Result of the prepare phase, used as input to the layout phase.
     * Treat this as an immutable value and only re-run Prepare() when the text content or style changes.
     */
    struct PreparedText
    {
        String             NormalizedText;     ///< Text after whitespace normalisation.
        Array<TextSegment> Segments;           ///< Pre-measured segments in logical order.
        Unit               HyphenWidth{ 0_u }; ///< Width of "-" (reserved for soft-hyphen support).
    };

    /**
     * @brief Represents a single shaped glyph used for rendering text, containing the glyph ID, pixel size, advance, and offset information.
     */
    struct ShapedGlyph
    {
        GlyphID   GlyphIndex{};
        FontUnit  XAdvance  { 0.f }, YAdvance{ 0.f }; ///< The advance of the glyph, to move the pen position after rendering this glyph.
        FontUnit  XOffset   { 0.f },  YOffset{ 0.f }; ///< The offset of the glyph, relative to the pen position when rendering.
    };

    /**
     * @brief Represents a single line of shaped text.
     */
    struct ShapedLine
    {
        u32  Start { 0 };
        u32  End   { 0 };
        Unit Width { 0_u };
    };

    /**
     * @brief Optimised data for rendering lines of text, produced by shaping the prepared text with ITextMetrics::Shape().
     */
    struct ShapedText
    {
        Array<ShapedGlyph> Glyphs; ///< The sequence of shaped glyphs that represent the rendered text.
        Array<ShapedLine>  Lines;  ///< Metadata about the lines in the shaped text.
        FontHandle         Font{}; ///< The font used for shaping the text, which is needed for rendering and glyph atlas lookups.

        Unit FontSize   { 0_u }; ///< The font size used for shaping the text, which is needed for rendering and layout calculations.
        Unit LineHeight { 0_u };
        Unit Ascender   { 0_u };
        Unit Descender  { 0_u };

        Unit MaxWidth          { 0_u }; ///< The maximum line width, used for overflow checks when rendering.
        Unit TotalHeight       { 0_u }; ///< The total height of the shaped text block, used for vertical alignment and spacing calculations.
        Unit UnderlinePosition { 0_u }; ///< The vertical position of the underline relative to the baseline, used for rendering underlines.
        Unit UnderlineThickness{ 0_u }; ///< The thickness of the underline, used for rendering underlines.

		/** @brief Returns the number of lines in the shaped text, which can be used for layout and spacing calculations. */
		u32 LineCount() const { return static_cast<u32>( Size( Lines ) ); }
    };

} // namespace RatUI
